# 2-D List and Numpy

In [2]:
l = input().strip().split(' ')
l #List of string

1 2 3


['1', '2', '3']

In [4]:
l = [int(i) for i in input().strip().split(' ')]
l #list of int

1 2 3


[1, 2, 3]

In [8]:
l = [[] for i in range(5)]
print(l)
l = [[j for j in range(5)] for i in range(5)]
l

[[], [], [], [], []]


[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [11]:
str = input().strip().split(' ')
n = int(str[0])
m = int(str[1])
l = [int(i) for i in input().strip().split(' ')]
out = []
for i in range(n):
    out.append([])
    for j in range(m):
        out[i].append(l[m*i+j])
out

2 3
1 2 3 4 5 6


[[1, 2, 3], [4, 5, 6]]

# Wave Print

In [12]:
n = len(out)
m = len(out[0])
for c in range(m):
    if c%2==0:
        for r in range(n):
            print(out[r][c] , end = " ")
    else:
        for r in range(n-1,-1,-1):
            print(out[r][c] , end = " ")


1 4 5 2 3 6 

# Numpy 

In [19]:
import numpy as np
l = [1,2,3]
arr = np.array(l)
print(arr[0])
arr

1


array([1, 2, 3])

In [23]:
l = np.zeros(10)
print(l)
print(l.dtype)
l = np.zeros(10,int)
print(l)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
float64
[0 0 0 0 0 0 0 0 0 0]


In [28]:
a = np.zeros((2,3) , int)
print(a)
a.shape

[[0 0 0]
 [0 0 0]]


(2, 3)

In [43]:
b = np.array([[1,2,3] ,[4,5,6] , [7,8,9]])
print(b)
print("----------")
print(b[:][1])
print("----------")
print(b[0:2][0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[4 5 6]
----------
[[1 2 3]
 [4 5 6]]


In [47]:
print(np.arange(10))
print(np.arange(2,14,2))

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12]


In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+2)
print(a ** 2)
print(a+b)
print(a.mean())
print(a.sum())

[3 4 5]
[1 4 9]
[5 7 9]
2.0
6


In [49]:
import math as m
d = ((a-b) ** 2).sum()
m.sqrt(d)

5.196152422706632

In [50]:
a.dot(b)

32

In [57]:
print(np.sum([[4, 1], [2, 5]] , axis = 1))
print(np.sum([[4, 1], [2, 5]] , axis = 0))

[5 7]
[6 6]
